import Link from 'next/link'

const address = 'Beside Royal Bawarchi Restaurant, New Hafeezpet, Marthanda Nagar, Hafeezpet, Hyderabad, Telangana 500049'
const phone = '+91-9891980070'
const email = 'info@kaanchwala.com'

export default function ContactPage() {
  const mapQuery = encodeURIComponent(address)
  return <main className="container py-16"><Link href="/" className="text-sm font-bold text-[#0644a4]">← Home</Link><div className="mt-6 grid gap-10 md:grid-cols-2"><div><p className="text-sm font-black uppercase tracking-wide text-[#0644a4]">Contact Us</p><h1 className="mt-2 text-4xl font-black text-[#10234d]">Get a Free Quote</h1><p className="mt-4 leading-7 text-slate-600">Tell us about your glass, mirror, window or interior requirement and our team will get back to you.</p><div className="mt-8 space-y-3 text-sm"><p>📍 {address}</p><p>☎ <a className="font-semibold hover:underline" href="tel:+919891980070">{phone}</a></p><p>✉ <a className="font-semibold hover:underline" href="mailto:info@kaanchwala.com">{email}</a></p><p>🕘 Mon - Sun: 9:00 AM - 7:00 PM</p><div className="flex flex-wrap gap-3"><a href="tel:+919891980070" className="inline-block rounded-md bg-[#0644a4] px-5 py-3 font-bold text-white">CALL NOW</a><a href="https://wa.me/919891980070" target="_blank" rel="noopener noreferrer" className="inline-block rounded-md bg-[#159447] px-5 py-3 font-bold text-white">WHATSAPP US</a></div></div></div><form className="rounded-xl border bg-white p-6 shadow-sm"><label className="block text-sm font-bold">Name<input name="name" required className="mt-2 w-full rounded border p-3" /></label><label className="mt-4 block text-sm font-bold">Phone<input name="phone" required type="tel" className="mt-2 w-full rounded border p-3" /></label><label className="mt-4 block text-sm font-bold">Requirement<textarea name="message" rows={5} required className="mt-2 w-full rounded border p-3" /></label><button type="submit" className="mt-5 rounded bg-[#0644a4] px-6 py-3 font-bold text-white">REQUEST QUOTE</button></form></div><section className="mt-10 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><iframe title="Kaanchwala location map" src={`https://www.google.com/maps?q=${mapQuery}&output=embed`} className="h-[360px] w-full border-0" loading="lazy" referrerPolicy="no-referrer-when-downgrade" /></section></main>
}
