import Link from 'next/link'

const hero = 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1500&q=84'
const cutaway = 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1100&q=84'

export default function AluminiumFramedPartitionsPage() {
  return (
    <main className="kw-page">
      <div className="container py-4 text-sm font-semibold text-slate-500"><Link href="/" className="text-[#0644a4]">Home</Link><span className="mx-2">›</span><Link href="/services" className="text-[#0644a4]">Services</Link><span className="mx-2">›</span><span>Aluminium Framed Partitions</span></div>
      <section className="border-y border-slate-200 bg-white"><div className="container grid items-center gap-8 py-8 md:grid-cols-2 md:py-14"><div><p className="kw-eyebrow">Office Glass Partitions</p><h1 className="kw-title mt-3 text-4xl md:text-5xl">Aluminium Framed Partitions</h1><p className="mt-5 max-w-xl text-lg leading-8 text-slate-600">Durable aluminium framing with modern glass panels for offices, cabins, meeting rooms and commercial interiors.</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><Link href="/contact" className="rounded-md bg-[#0644a4] px-6 py-3 text-center font-bold text-white">GET FREE QUOTE</Link><a href="https://wa.me/919891980070" className="rounded-md border border-slate-300 px-6 py-3 text-center font-bold text-[#10234d]">WHATSAPP US</a></div></div><div className="overflow-hidden rounded-xl shadow-soft"><img src={hero} alt="Aluminium framed office glass partitions" className="h-[280px] w-full object-cover md:h-[390px]" /></div></div></section>
      <section className="kw-section"><div className="container grid items-center gap-8 md:grid-cols-2"><div><p className="kw-eyebrow">Why Choose It</p><h2 className="kw-title mt-2 text-3xl md:text-4xl">A clean, durable partition system</h2><div className="mt-6 grid gap-3 sm:grid-cols-2">{['Strong aluminium framing','Clear and frosted glass options','Custom office layouts','Easy maintenance','Professional finish','Designed for long-term use'].map((item) => <div key={item} className="kw-card p-4 font-bold text-[#10234d]">✓ {item}</div>)}</div></div><div className="overflow-hidden rounded-xl border border-slate-200 bg-white p-2 shadow-soft"><img src={cutaway} alt="Aluminium framed glass partition detail" className="h-[300px] w-full rounded-lg object-cover md:h-[390px]" /></div></div></section>
      <section className="kw-section bg-[#f7faff]"><div className="container"><p className="kw-eyebrow">Applications</p><h2 className="kw-title mt-2 text-3xl">Where aluminium framed partitions work well</h2><div className="mt-7 grid gap-5 md:grid-cols-3">{['Private Office Cabins','Meeting Rooms','Reception Areas','Manager Cabins','Workstation Dividers','Commercial Interiors'].map((item) => <article key={item} className="kw-card p-6"><h3 className="font-black text-[#10234d]">{item}</h3><p className="mt-2 text-sm leading-6 text-slate-500">Planned around your measurements, privacy requirements and interior finish.</p></article>)}</div></div></section>
      <section className="kw-section"><div className="container rounded-xl bg-[#0644a4] p-7 text-white md:p-10"><h2 className="text-3xl font-black">Ready to plan your partition?</h2><p className="mt-2 max-w-2xl text-blue-100">Request a site visit and quotation from Kaanchwala.</p><Link href="/contact" className="mt-6 inline-block rounded-md bg-white px-6 py-3 font-bold text-[#0644a4]">REQUEST A QUOTE</Link></div></section>
    </main>
  )
}
